version: '3.4'
services:
  rocket:
    container_name: rocket
    build: ./Services/Rocket
    ports:
      - "4001:3010"
    networks:
      - blueorigin
      
  chiefrocket:
    container_name: chief-rocket-department
    build: ./Services/ChiefRocketDepartment
    ports:
      - "4002:3010"
    networks:
      - blueorigin

  poll:
    container_name: poll
    build: ./Services/Poll
    ports:
      - "4003:3010"
    networks:
      - blueorigin

  launchweather:
    container_name: launch-weather-officer
    build: ./Services/LaunchWeatherOfficer
    ports:
      - "4004:3010"
    networks:
      - blueorigin

  weathersupplier:
    container_name: weather-supplier
    build: ./Services/WeatherSupplier
    ports:
      - "4005:3010"
    networks:
      - blueorigin

  richardinterface:
    container_name: richard-interface
    build: ./Services/RichardInterface
    ports:
      - "4006:3010"
    networks:
      - blueorigin

  telemetry:
    container_name: telemetry
    build: ./Services/Telemetry
    ports:
      - "4007:3010"
    networks:
      - blueorigin

  payloaddepartment:
    container_name: payload-department
    build: ./Services/PayloadDepartment
    ports:
      - "4008:3010"
    networks:
      - blueorigin

  client:
    container_name: client
    build: ./Services/Client
    ports:
      - "4009:3010"
    networks:
      - blueorigin

networks:
  blueorigin: