version: '3.4'
services:
  rocket:
    container_name: rocket
    build: ./Services/Rocket
    ports:
      - "4001:4001"
    networks:
      - blueorigin

  chief_rocket:
    container_name: chief-rocket-department
    build: ./Services/ChiefRocketDepartment
    ports:
      - "4002:4002"
    networks:
      - blueorigin

  poll:
    container_name: poll
    build: ./Services/Poll
    ports:
      - "4003:4003"
    networks:
      - blueorigin

  launch_weather:
    container_name: launch-weather-officer
    build: ./Services/LaunchWeatherOfficer
    ports:
      - "4004:4004"
    networks:
      - blueorigin

  weather_supplier:
    container_name: weather-supplier
    build: ./Services/WeatherSupplier
    ports:
      - "4005:4005"
    networks:
      - blueorigin

  mission_commander_interface:
    container_name: mission_commander-interface
    build: ./Services/MissionCommanderInterface
    ports:
      - "4006:4006"
    networks:
      - blueorigin

  telemetry:
    container_name: telemetry
    build: ./Services/Telemetry
    ports:
      - "4007:4007"
    networks:
      - blueorigin

  payload_department:
    container_name: payload-department
    build: ./Services/PayloadDepartment
    ports:
      - "4008:4008"
    networks:
      - blueorigin

  client:
    container_name: client
    build: ./Services/Client
    ports:
      - "4009:4009"
    networks:
      - blueorigin

  webcasting:
    container_name: webcasting
    build: ./Services/Webcasting
    ports:
      - "4010:4010"
    networks:
      - blueorigin

  rocket_telemetry:
    container_name: rocket_telemetry
    build: ./Services/RocketTelemetry
    ports:
      - "4011:4011"
    networks:
      - blueorigin

  rocket_poll:
    container_name: rocket_poll
    build: ./Services/RocketPoll
    ports:
      - "4012:4012"
    networks:
      - blueorigin

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - blueorigin

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "Poll:1:1,responsePollRocket:1:1,responsePollWeather:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - blueorigin

networks:
  blueorigin: 